default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: database

development:
  <<: *default
  database: database_orders_development

test:
  <<: *default
  database: database_orders_test

production:
  <<: *default
  database: database_orders_production
