default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: database
  database: <%= ENV['POSTGRES_DB'] %>

test:
  <<: *default
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: database
  database: <%= ENV['POSTGRES_DB'] %>

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>